import { SpaceItem, AmenityItem, SiteConfig, Enquiry } from '../types';

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  brandName: 'THE GRID',
  brandSubtitle: 'POWERED BY CASTILLO',
  phone: '9562868661',
  phoneFormatted: '+91 9562868661',
  whatsappNumber: '919562868661',
  whatsappMessageTemplate: "Hi, I'd like to know more about [SPACE_NAME] at THE GRID",
  email: 'thegridbycastillo@gmail.com',
  instagram: '@the__grid___',
  instagramUrl: 'https://www.instagram.com/the__grid___?igsi=eTV0NHk2ZncxZnd6',
  address: '1st Floor, Phase 2, Hilite Business Park, Calicut',
  floorNotice: 'THE GRID is on the 1st floor of Hilite Business Park, Phase 2 — no lift queues, no long stair climbs before your first meeting.',
  heroHeadline: 'Skip the stress. Skip Expensive rent. Just work.',
  heroPosterQuestion: 'Which One Would You Choose?',
  heroSubhead: "THE GRID gives Calicut's freelancers, startups and small teams a fully furnished workspace at Hilite Business Park — desks, cabins and virtual offices from ₹999/month.",
  whyCoworkingHeadline: 'Why coworking works',
  whyCoworkingPoints: [
    'Cost-effective and affordable',
    'Networking and collaboration opportunities',
    'Professional work environment, increased productivity',
    'Great for freelancers, startups and remote workers',
    'Saves time on office management',
  ],
  whyCoworkingDescriptions: [
    'Desks and cabins start at ₹3,500 and a virtual office at ₹999/month — a fraction of what a private office lease in Calicut would cost you.',
    'Shared desks and a common games & fun zone put you next to other founders and freelancers, not alone in a rented room.',
    "Fully furnished desks, air conditioning and high-speed WiFi mean you're not fixing office problems — you're just working.",
    'No lease, no deposit lock-in, no hiring an office manager — scale from a single hot desk to a 24-seater as your team grows.',
    'Pantry, parking, courier handling and a signed name board are already sorted — you skip the setup and start working from day one.',
  ],
  bannerText: '✨ Desks & Private Cabins available for immediate walk-in on 1st Floor, Hilite Business Park!',
  bannerEnabled: true,
  googleMapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3913.376258079549!2d75.83350227583623!3d11.23377755060193!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba65a2979201a09%3A0x8673a5a7516d2ca8!2sHiLITE%20Business%20Park!5e0!3m2!1sen!2sin!4v1709600000000!5m2!1sen!2sin',
  promoPopup: {
    enabled: true,
    tag: 'FLOOR UPDATE · HILITE PHASE 2',
    headline: '4-SEATER CABIN JUST OPENED',
    description: 'Immediate move-in available on 1st Floor. Plug-and-play with dedicated AC & fiber WiFi.',
    ctaText: 'Ask for floor walkthrough',
    floorLocation: '1st Floor',
    whatsappMessage: 'Hi, I saw the 4-seater private cabin update at THE GRID Hilite Park. Is it available?',
  },
};

export const DEFAULT_SPACES: SpaceItem[] = [
  {
    id: 'space-hot-desk',
    name: 'Hot desk / co-working space',
    price: 'Starting from ₹3,500',
    unit: 'per month',
    badge: 'FLEXIBLE',
    seatsInfo: '1 Seat (Flexible / Dedicated)',
    description: "A single desk in THE GRID's shared floor at Hilite Business Park, Calicut — bring a laptop and you're set up in minutes.",
    features: [
      'High-speed WiFi',
      'Fully air-conditioned',
      'Coffee machine access',
      'Games & fun zone',
      'Accessible location',
    ],
    isAvailable: true,
    highlightTag: 'Instant Setup',
    iconType: 'desk',
    order: 1,
    imageUrl: 'https://i.postimg.cc/L8LVYHhb/file-00000000eea881f89cf02d346c35d8df.png',
    imageAlt: 'Hot desk coworking space at THE GRID, Hilite Business Park, Calicut',
  },
  {
    id: 'space-private-cabin',
    name: 'Private cabin (4 / 6 / 8 / 12 seater)',
    price: 'Starting from ₹3,500',
    unit: 'per seat / month',
    badge: 'MOST POPULAR',
    seatsInfo: '4, 6, 8 or 12 Seater',
    description: 'Fully furnished private cabins for small teams who need a closed door and their own space, sized from 4 to 12 seats.',
    features: [
      'Fully furnished',
      'Fully air-conditioned',
      'High-speed WiFi',
      'Meeting room access',
      'Pantry & parking',
    ],
    isAvailable: true,
    highlightTag: 'Privacy & Focus',
    iconType: 'cabin',
    order: 2,
    imageUrl: 'https://i.postimg.cc/CLY8Pj1T/file-00000000810081f78c5c11097a9ecc9e.png',
    imageAlt: 'Private cabin workspace for teams at THE GRID, Hilite Business Park, Calicut',
  },
  {
    id: 'space-managed-office',
    name: 'Managed office space (up to 24 seaters)',
    price: 'Starting from ₹3,500',
    unit: 'per seat / month',
    badge: 'GROWING TEAMS',
    seatsInfo: 'Scalable up to 24 Seats',
    description: 'A fully furnished managed office for growing teams, available in 3, 4, 5 and 8-seater configurations and scalable up to 24 seats.',
    features: [
      'Fully furnished',
      'Free WiFi',
      'Meeting rooms',
      'Pantry',
      'Parking',
      'Games & fun zone',
    ],
    isAvailable: true,
    highlightTag: 'Zero Hassle',
    iconType: 'office',
    order: 3,
    imageUrl: 'https://i.postimg.cc/DzykBYVK/file-000000002c688207aab359367e133d65.png',
    imageAlt: 'Managed office space up to 24 seats at THE GRID, Hilite Business Park, Calicut',
  },
  {
    id: 'space-virtual-office',
    name: 'Virtual office',
    price: '₹999/month',
    unit: 'all-inclusive',
    badge: 'BEST VALUE',
    seatsInfo: 'Business Address & Compliances',
    description: 'A registered business address at Hilite Business Park for founders who need paperwork sorted without renting a desk.',
    features: [
      'Prime location address',
      'Business registration & office support',
      'Inward courier management',
      'Name board / signage',
      'Office assistance',
      'Workstation access',
      'LLP & Pvt Ltd registration',
    ],
    isAvailable: true,
    highlightTag: 'Diamond Badge ₹999',
    iconType: 'virtual',
    order: 4,
    imageUrl: 'https://i.postimg.cc/TPPFrLm5/file-00000000725882089b00296a80df7f78.png',
    imageAlt: 'Virtual office and conference setup at THE GRID, Hilite Business Park, Calicut',
  },
];

export const DEFAULT_AMENITIES: AmenityItem[] = [
  {
    id: 'amenity-furnished',
    title: 'Fully furnished',
    description: 'Desks, chairs and cabins ready to walk into',
    icon: 'sofa',
    enabled: true,
  },
  {
    id: 'amenity-ac',
    title: 'Fully air-conditioned',
    description: 'Every cabin and desk zone climate controlled',
    icon: 'snowflake',
    enabled: true,
  },
  {
    id: 'amenity-location',
    title: 'Accessible location',
    description: '1st floor, Hilite Business Park, Phase 2, Calicut',
    icon: 'map-pin',
    enabled: true,
  },
  {
    id: 'amenity-wifi',
    title: 'High-speed WiFi',
    description: 'No queuing for bandwidth, enterprise grade line',
    icon: 'wifi',
    enabled: true,
  },
  {
    id: 'amenity-games',
    title: 'Games & fun zone',
    description: "A break room that isn't just a corridor",
    icon: 'gamepad',
    enabled: true,
  },
  {
    id: 'amenity-coffee',
    title: 'Coffee machine',
    description: 'On tap, no separate charge for daily brew',
    icon: 'coffee',
    enabled: true,
  },
];

export const INITIAL_SAMPLE_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-101',
    name: 'Rahul K. Nair',
    phone: '9847123456',
    email: 'rahul.tech@gmail.com',
    spaceType: 'Private cabin (4 / 6 / 8 / 12 seater)',
    seatsNeeded: '6 seats',
    message: 'We are a 6-member tech team looking for immediate move-in from next Monday. Need to check cabin availability.',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    status: 'new',
    notes: 'Called once, requested floor walkthrough at 3 PM.',
  },
  {
    id: 'enq-102',
    name: 'Ananya S.',
    phone: '9446098765',
    email: 'ananya.design@outlook.com',
    spaceType: 'Hot desk / co-working space',
    seatsNeeded: '1 seat',
    message: 'Freelance UI designer. Need a quiet desk with fast WiFi and coffee access for 3 months.',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    status: 'contacted',
    notes: 'Sent WhatsApp details with desk plan.',
  },
  {
    id: 'enq-103',
    name: 'Faisal Mohammed',
    phone: '9995112233',
    email: 'faisal@calicutventures.in',
    spaceType: 'Virtual office',
    seatsNeeded: 'Virtual',
    message: 'Need GST and Pvt Ltd company registration address at Hilite Business Park Phase 2.',
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    status: 'booked',
    notes: 'Agreement signed, onboarded for ₹999/mo plan.',
  },
];
